library(dplyr)
library(readr)
library(stringr)
library(Rcpp)
library(sf)
library(ggplot2)

# in your folder where you run the image you will need:
# 1. st4_conus.YYYYMMDDHH.01h.txt (this should be generated by the previous container)
# 2. an AOI.csv with grib_id, hrap_x, hrap_y, center_lon, center_lat for grib2 cells [texas_buffer_spatial_join.csv]
# 3. a shapefile of AOI with grib IDs. [hrap_poly_clip.shp]


#read in your csv for AOI it should have grib_id, hrap_x, hrap_y, center_lon, center_lat for grib2 cells
aoi_texas_buffer<-read_csv(paste0(getwd(),"/texas_buffer_spatial_join.csv"))

#starts with st4_conus. and ends with .txt
raw_grib2_text<-list.files(getwd(),pattern = "^st4_conus.*.txt$",full.names=FALSE)

#h<-list.files(getwd(),pattern = "^st4_conus.*.txt$",full.names=FALSE)

for (h in raw_grib2_text) {
  
  name <- h |>
    str_replace("st4_conus.", "t") |>
    str_replace(".01h.txt","")
  
 aa<-read_csv(paste0(getwd(),"/",h), col_names=FALSE) %>%
    setNames(c("x1","x2","x3","x4","center_lon","center_lat",name)) %>%
    select(-x1,-x2,-x3,-x4)   
    
  # joins by "center_lon", "center_lat"
  bb<- left_join(aoi_texas_buffer,aa,by=NULL)
    }  


shape <- st_read(paste0(getwd(),"/hrap_poly_clip.shp"))

mod_shape <- shape %>% 
  left_join(bb, by = "grib_id") 

#st4 <- ggplot(data = mod_shape) +
#      geom_sf(aes(fill = get(`name`)), color = NA)+
#      ggtitle(name)

st4 <- ggplot(data =mod_shape) +
  geom_sf(aes(fill = get(`name`)), color = NA)+
  scale_fill_stepsn(colours=c("#61686D","#82D3F0","#83B2C3","#0826A2","#22FE05","#2CAC1B","#248418", "#F6FB07", "#FFE890", "#FFC348","#E01E17", "#A92B26","#8C302C","#CC17DA", "#AE6DB3","white" ),
                    breaks = c(.001, 2.54, 6.35, 12.7, 19.05, 25.4, 38.1, 50.8, 63.5, 76.2, 101.6, 127, 152.4, 203.2, 254),
                    limits=c(0,381),
                    values = scales::rescale(c(.0005, 1.40, 4.44, 9.52, 15.87, 22.22, 31.75, 44.45, 57.15, 69.85, 88.9, 114.3, 139.7, 177.8, 228.6, 317.5), 
                                             from = c(0, 381)),
                    show.limits = TRUE)


ggsave (filename=paste0("stg4_drop",".png"),plot = st4, width = 5.25, height=4, units="in")


